title: "Timothy J Scholtz"
author: "Tim Scholtz"
description: "<b style=\"color: #fec601;\">Computer Engineering </b> student at the <b style=\"color: #2364aa;\">University at Buffalo </b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Home}
  - {url: "CV.pdf" , title: CV}
  - {file: "blog.html", title: Projects}
  - {file: "README.md" , title: About me }

hidden_links:
  - {url: "BioVoice_Presentation_PDF_TimothyScholtz.pdf" }

  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: LinkedIn, icon: linkedin, url: "https://https://www.linkedin.com/in/t-j-scholtz/"}
  - {title: Email, icon: envelope, url: "mailto:tim.scholtz@outlook.com"}
  - {title: Github, icon: github, url: "https://github.com/t-scholtz"}
  - {title: Cedar, icon: tree, url: "https://cedar-tools.com/"}
  - {title: Spotify, icon: spotify, url: "https://open.spotify.com/user/mwk1wzobiq06le7tw3govdzy8"}

  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
